CREATE SCHEMA IF NOT EXISTS ewm_comments;

CREATE TABLE IF NOT EXISTS event_comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_on   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    text         VARCHAR(2000)               NOT NULL,
    author_id    BIGINT                      NOT NULL,
    event_id     BIGINT                      NOT NULL,
    state        VARCHAR(20)                 NOT NULL,
    CONSTRAINT COMMENTS_PK PRIMARY KEY (id),
    CONSTRAINT chk_comment_state CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED'))
);
