server:
  port: 0

spring:
  application:
    name: aggregator

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

aggregator:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: aggregator
    topic:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
