spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments,/users/*/comments/**,/admin/comments,/admin/comments/**
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests,/users/*/requests/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/events,/events/**,/admin/events/**,/users/*/events,/users/*/events/**,/compilations,/compilations/**,/admin/compilations,/admin/compilations/**,/categories,/categories/**,/admin/categories,/admin/categories/**
        - id: stats_server_route
          uri: lb://stats-server
          predicates:
            - Path=/hit,/stats/**


server:
  port: 8080