server:
  port: 0

grpc:
  server:
    port: 0

spring:
  datasource:
    url: ${ANALYZER_DB_URL:jdbc:postgresql://localhost:5432/ewm_analyzer}
    username: ${ANALYZER_DB_USER:postgres}
    password: ${ANALYZER_DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  application:
    name: analyzer

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

analyzer:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: analyzer
    topic:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      gRPC_port: ${grpc.server.port}
